services:
  scenario-rotation:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SERVER_CONTAINER_NAMES=koth1-koth-reforged-1-1,koth2-koth-reforged-2-1,koth3-koth-reforged-3-1,arma-koth-reforged-1-1,arma2-koth-reforged-2-1,arma3-koth-reforged-3-1